name: plantpal
description: "PlantPal – Instant Plant Care & Diagnosis"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.9
  
  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Backend & Database
  supabase_flutter: ^2.0.2
  
  # Navigation
  go_router: ^12.1.3
  
  # Image & Camera
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  
  # Notifications
  flutter_local_notifications: ^16.3.3
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.2.1
  
  # Logging
  logger: ^2.0.2+1
  
  # UI Components
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.10
  freezed: ^2.5.7
  json_serializable: ^6.9.0

# Force newer versions to fix compatibility issues
dependency_overrides:
  custom_lint_core: ^0.6.0
  custom_lint: ^0.6.0
  analyzer: ^6.11.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/ 